server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Kui päring tuleb /mangud/... kujul (välisproxy ei eemaldanud prefiksit)
    location /mangud/ {
        rewrite ^/mangud/(.*)$ /$1 last;
    }
    location = /mangud {
        return 302 /mangud/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Helid
    location /sounds/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=86400";
    }

    location /pb/ {
        proxy_pass http://pocketbase:8090/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 86400;
    }

    location /mangud/pb/ {
        proxy_pass http://pocketbase:8090/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 86400;
    }
}
