import type { MiljonarQuestion } from './types'

export const MILJONAR_KLASSIKA_QUESTIONS: MiljonarQuestion[] = [
  // 1. 100 €
  {
    id: 'k-1',
    tier: 1,
    prize: 100,
    q: 'Mitu minutit on ühes täistunnis?',
    choices: ['30 minutit', '60 minutit', '100 minutit', '120 minutit'],
    correct: 1,
    hostNote: 'Lihtne soojendusküsimus: tund koosneb 60 minutist.',
    funFact: 'Tundide jaotamise 60 minutiks võtsid kasutusele juba iidsed babüloonlased.',
    difficulty: 'easy',
  },
  // 2. 200 €
  {
    id: 'k-2',
    tier: 2,
    prize: 200,
    q: 'Millise spordiala kuulsaim võistlus on Tour de France?',
    choices: ['Jalgrattasõit', 'Vormel 1', 'Purjetamine', 'Maratonijooks'],
    correct: 0,
    hostNote: 'Tour de France on maailma tuntuim mitmepäevane jalgrattatuur.',
    funFact: 'Esimene Tour de France toimus juba aastal 1903.',
    difficulty: 'easy',
  },
  // 3. 300 €
  {
    id: 'k-3',
    tier: 3,
    prize: 300,
    q: 'Mis on Eesti Vabariigi ametlik rahvuslind?',
    choices: ['Rukkilill', 'Suitsupääsuke', 'Kuldnokk', 'Metskits'],
    correct: 1,
    hostNote: 'Suitsupääsuke valiti Eesti rahvuslinnuks 1962. aastal.',
    funFact: 'Rukkilill on rahvuslill ja hunt on rahvusloom.',
    difficulty: 'easy',
  },
  // 4. 500 €
  {
    id: 'k-4',
    tier: 4,
    prize: 500,
    q: 'Milline neist planeetidest on Päikesesüsteemis Päikesele kõige lähemal?',
    choices: ['Veenus', 'Marss', 'Merkuur', 'Maa'],
    correct: 2,
    hostNote: 'Merkuur on Päikesesüsteemi väikseim ja Päikesele lähim planeet.',
    funFact: 'Merkuuril puudub atmosfäär, mistõttu öö ja päeva temperatuuride vahe on üle 500 kraadi.',
    difficulty: 'easy',
  },
  // 5. 1 000 € (ESIMENE TURVASUMMA!)
  {
    id: 'k-5',
    tier: 5,
    prize: 1000,
    q: 'Kes oli kirjandusteose "Tõde ja õigus" autor?',
    choices: ['Oskar Luts', 'Eduard Vilde', 'A. H. Tammsaare', 'Jaan Kross'],
    correct: 2,
    hostNote: 'A. H. Tammsaare viieköiteline eepiline romaan ilmus aastatel 1926–1933.',
    funFact: 'Tammsaare kodanikunimi oli Anton Hansen.',
    difficulty: 'easy',
  },
  // 6. 2 000 €
  {
    id: 'k-6',
    tier: 6,
    prize: 2000,
    q: 'Millise keemilise elemendi tähis perioodilisustabelis on Au?',
    choices: ['Hõbe', 'Kuld', 'Alumiinium', 'Raud'],
    correct: 1,
    hostNote: 'Au pärineb ladinakeelsest sõnast "Aurum" ehk särav koit.',
    funFact: 'Hõbeda sümbol on Ag (Argentum) ja raua oma Fe (Ferrum).',
    difficulty: 'medium',
  },
  // 7. 4 000 €
  {
    id: 'k-7',
    tier: 7,
    prize: 4000,
    q: 'Milline linn on Austraalia pealinn?',
    choices: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correct: 2,
    hostNote: 'Tihti arvatakse Sydney või Melbourne, kuid kompromissina ehitati pealinnaks Canberra.',
    funFact: 'Canberra valiti pealinnaks 1908. aastal just Sydney ja Melbourne\'i rivaalitsemise lahendamiseks.',
    difficulty: 'medium',
  },
  // 8. 8 000 €
  {
    id: 'k-8',
    tier: 8,
    prize: 8000,
    q: 'Mis aastal uppus ookeaniaurik Titanic?',
    choices: ['1905', '1912', '1918', '1923'],
    correct: 1,
    hostNote: 'Titanic põrkas jäämäega kokku ööl vastu 15. aprilli 1912.',
    funFact: 'Laev oli teel Southamptonist New Yorki oma esimesel reisil.',
    difficulty: 'medium',
  },
  // 9. 16 000 €
  {
    id: 'k-9',
    tier: 9,
    prize: 16000,
    q: 'Milline neist pillidest kuulub puupuhkpillide perekonda, kuigi on valmistatud metallist?',
    choices: ['Trompet', 'Saksofon', 'Tuuba', 'Tromboon'],
    correct: 1,
    hostNote: 'Saksofon loetakse puupuhkpilliks selle huuliku ja pilliroost pilliroolehe tõttu.',
    funFact: 'Pilli leiutas Belgia pillimeister Adolphe Sax 1840. aastatel.',
    difficulty: 'medium',
  },
  // 10. 32 000 € (TEINE TURVASUMMA!)
  {
    id: 'k-10',
    tier: 10,
    prize: 32000,
    q: 'Mis on maailma sügavaim järv?',
    choices: ['Kaspia meri', 'Baikali järv', 'Tanganjika järv', 'Ülemjärv'],
    correct: 1,
    hostNote: 'Baikali järve sügavus on 1642 meetrit ja see sisaldab umbes 20% maailma vedelast mageveest.',
    funFact: 'Baikali järv on ka maailma vanim mageveekogu (umbes 25 miljonit aastat).',
    difficulty: 'hard',
  },
  // 11. 64 000 €
  {
    id: 'k-11',
    tier: 11,
    prize: 64000,
    q: 'Kes maalis kuulsa kunstiteose "Tütarlaps pärlkõrvarõngaga"?',
    choices: ['Johannes Vermeer', 'Rembrandt', 'Vincent van Gogh', 'Claude Monet'],
    correct: 0,
    hostNote: 'Hollandi kuldajastu meister Johannes Vermeer lõi selle teose umbes 1665. aastal.',
    funFact: 'Maali nimetatakse sageli ka "Põhjamaade Mona Lisaks".',
    difficulty: 'hard',
  },
  // 12. 125 000 €
  {
    id: 'k-12',
    tier: 12,
    prize: 125000,
    q: 'Millise riigi territooriumil asub Aafrika kõrgeim mäetipp Kilimanjaro?',
    choices: ['Keenia', 'Tansaania', 'Uganda', 'Etioopia'],
    correct: 1,
    hostNote: 'Kilimanjaro (5895 m) asub Ida-Aafrikas Tansaania kirdeosas Keenia piiri lähedal.',
    funFact: 'Kuigi see asub ekvaatori lähedal, on selle tipus liustikud.',
    difficulty: 'hard',
  },
  // 13. 250 000 €
  {
    id: 'k-13',
    tier: 13,
    prize: 250000,
    q: 'Kes oli esimene inimene kosmoses, kes tegi tiiru ümber Maa?',
    choices: ['Neil Armstrong', 'Juri Gagarin', 'Buzz Aldrin', 'Aleksei Leonov'],
    correct: 1,
    hostNote: 'Juri Gagarin sooritas oma ajaloolise lennu kosmoselaevaga Vostok 1 12. aprillil 1961.',
    funFact: 'Lend kestis 108 minutit ning Gagarin maandus langevarjuga.',
    difficulty: 'hard',
  },
  // 14. 500 000 €
  {
    id: 'k-14',
    tier: 14,
    prize: 500000,
    q: 'Milline oli Rooma keisri Nero kuulus viimane lause enne surma?',
    choices: [
      'Veni, vidi, vici',
      'Qualis artifex pereo',
      'Alea iacta est',
      'Et tu, Brute',
    ],
    correct: 1,
    hostNote: 'Traditsiooni kohaselt hüüatas Nero: "Qualis artifex pereo!" ehk "Milline kunstnik minus hukkub!"',
    funFact: '"Alea iacta est" (Liisk on heidetud) kuulus Julius Caesarile Rubicot ületades.',
    difficulty: 'expert',
  },
  // 15. 1 000 000 € (MILJONIKÜSIMUS!)
  {
    id: 'k-15',
    tier: 15,
    prize: 1000000,
    q: 'Millise Euroopa riigi lipul on kujutatud ainsa riigina maailmas Piiblit?',
    choices: ['Vatikan', 'Dominikaani Vabariik', 'San Marino', 'Andorra'],
    correct: 1,
    hostNote: 'Dominikaani Vabariigi lipu vapil on avatud Piibel Johannese evangeeliumi 8:32 salmiga: "Tõde teeb teid vabaks".',
    funFact: 'San Marino lipul on kolm torni ja Vatikanil Peetruse võtmed, kuid avatud Piibel on ainult Dominikaani Vabariigil.',
    difficulty: 'expert',
  },
  // BACKUP QUESTIONS (For "Switch Question" lifeline)
  {
    id: 'k-backup-1',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Milline on maailma pikim mäestik maismaal?',
    choices: ['Himaalaja', 'Andid', 'Kaljumäestik', 'Uural'],
    correct: 1,
    hostNote: 'Andid Lõuna-Ameerikas ulatuvad umbes 7000 kilomeetri pikkuselt.',
    funFact: 'Himaalaja on maailma kõrgeim, kuid Andid on pikim.',
    difficulty: 'medium',
  },
  {
    id: 'k-backup-2',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Kes avastas penitsilliini 1928. aastal?',
    choices: ['Louis Pasteur', 'Alexander Fleming', 'Robert Koch', 'Edward Jenner'],
    correct: 1,
    hostNote: 'Šoti teadlane Alexander Fleming märkas hallituse antibakteriaalset toimet.',
    funFact: 'Avastus toimus juhuslikult, kui Fleming jättis Petri tassi puhkuse ajaks laborisse.',
    difficulty: 'hard',
  },
]

export const MILJONAR_EESTI_QUESTIONS: MiljonarQuestion[] = [
  {
    id: 'e-1',
    tier: 1,
    prize: 100,
    q: 'Mis on Eesti Vabariigi pealinn?',
    choices: ['Tartu', 'Pärnu', 'Tallinn', 'Narva'],
    correct: 2,
    hostNote: 'Tallinn on Eesti pealinn ja suurim linn.',
    difficulty: 'easy',
  },
  {
    id: 'e-2',
    tier: 2,
    prize: 200,
    q: 'Milline neist on Eesti traditsiooniline rahvustoit, eriti vastlapäeval?',
    choices: ['Hernesupp ja vastlakukkel', 'Pelmeenid', 'Pitsa', 'Sushi'],
    correct: 0,
    hostNote: 'Vastlapäeva lahutamatud osad on vahukoorega vastlakukkel ja suitsulihaga hernesupp.',
    difficulty: 'easy',
  },
  {
    id: 'e-3',
    tier: 3,
    prize: 300,
    q: 'Mis värvid on Eesti riigilipul ülevalt alla lugedes?',
    choices: ['Must, sinine, valge', 'Sinine, must, valge', 'Valge, must, sinine', 'Sinine, valge, must'],
    correct: 1,
    hostNote: 'Sinine, must ja valge – taevas, muld ja lootus.',
    difficulty: 'easy',
  },
  {
    id: 'e-4',
    tier: 4,
    prize: 500,
    q: 'Milline on Eesti suurim saar pindalalt?',
    choices: ['Hiiumaa', 'Saaremaa', 'Muhu', 'Vormsi'],
    correct: 1,
    hostNote: 'Saaremaa pindala on 2673 km².',
    difficulty: 'easy',
  },
  {
    id: 'e-5',
    tier: 5,
    prize: 1000,
    q: 'Mis aastal toimus Eestis esimene üldlaulupidu Tartus?',
    choices: ['1869', '1918', '1890', '1928'],
    correct: 0,
    hostNote: '1869. aasta juunis toimus Tartus Johann Voldemar Jannseni eestvedamisel esimene laulupidu.',
    difficulty: 'easy',
  },
  {
    id: 'e-6',
    tier: 6,
    prize: 2000,
    q: 'Kelle portree oli Eesti 500-kroonisel rahatähel enne euro tulekut?',
    choices: ['Carl Robert Jakobson', 'A. H. Tammsaare', 'Kristjan Raud', 'Jakob Hurt'],
    correct: 1,
    hostNote: '500-kroonisel oli kirjanik A. H. Tammsaare. Jakob Hurt oli 10-kroonisel ja Jakobson 500-kroonisel polnud (ta oli 5-kroonisel).',
    difficulty: 'medium',
  },
  {
    id: 'e-7',
    tier: 7,
    prize: 4000,
    q: 'Milline Eesti helilooja on tuntud oma "tintinnabuli" stiili poolest?',
    choices: ['Veljo Tormis', 'Arvo Pärt', 'Erkki-Sven Tüür', 'Eduard Tubin'],
    correct: 1,
    hostNote: 'Arvo Pärt on maailmas enim esitatud elav helilooja.',
    difficulty: 'medium',
  },
  {
    id: 'e-8',
    tier: 8,
    prize: 8000,
    q: 'Mis on Eesti pikim jõgi?',
    choices: ['Pärnu jõgi', 'Emajõgi', 'Võhandu jõgi', 'Narva jõgi'],
    correct: 2,
    hostNote: 'Võhandu jõgi on 162 km pikk. Pärnu jõgi on 144 km.',
    difficulty: 'medium',
  },
  {
    id: 'e-9',
    tier: 9,
    prize: 16000,
    q: 'Kes oli Eesti Vabariigi esimene president pärast iseseisvuse taastamist?',
    choices: ['Arnold Rüütel', 'Lennart Meri', 'Toomas Hendrik Ilves', 'Konstantin Päts'],
    correct: 1,
    hostNote: 'Lennart Meri valiti presidendiks 1992. aastal ja oli ametis kuni 2001. aastani.',
    difficulty: 'medium',
  },
  {
    id: 'e-10',
    tier: 10,
    prize: 32000,
    q: 'Millises Eesti maakonnas asub Kaali kraatriväli?',
    choices: ['Hiiumaal', 'Saaremaal', 'Läänemaal', 'Pärnumaal'],
    correct: 1,
    hostNote: 'Kaali meteoriidikraater asub Saaremaal, umbes 18 km Kuressaarest.',
    difficulty: 'hard',
  },
  {
    id: 'e-11',
    tier: 11,
    prize: 64000,
    q: 'Kes võitis 2000. aasta Sydney olümpiamängudel Eestile kuldmedali judos?',
    choices: ['Erki Nool (kuld kümnevõistluses)', 'Aleksei Budõlin (pronks)', 'Indrek Pertelson (pronks)', 'Mitte keegi (judos võideti 2 pronksi)'],
    correct: 3,
    hostNote: 'Kaval küsimus! Sydneys võitis ainsa kulla Erki Nool; judokad Pertelson ja Budõlin tõid mõlemad pronksi.',
    difficulty: 'hard',
  },
  {
    id: 'e-12',
    tier: 12,
    prize: 125000,
    q: 'Mis nime kandis esimene eestikeelne aabits, mille koostas Bengt Gottfried Forselius 1684. aasta paiku?',
    choices: ['Kukeaabits', 'Wastne Testament', 'Eesti-Ma Rahwa Kalender', 'Wanemuise laul'],
    correct: 0,
    hostNote: 'Forseliuse aabitsat hakati nimetama Kukeaabitsaks kuke pildi järgi, mis sümboliseeris ärksust.',
    difficulty: 'hard',
  },
  {
    id: 'e-13',
    tier: 13,
    prize: 250000,
    q: 'Milline Eesti saar oli Nõukogude ajal suletud eriti salajase mereväe allveelaevade treeningkeskuse tõttu?',
    choices: ['Osmussaar', 'Paldiski (poolsaar/linn)', 'Pakri saared', 'Naissaar'],
    correct: 1,
    hostNote: 'Paldiski oli kinnine tuumaallveelaevade õppekeskusega sõjaväelinnak kahe tuumareaktoriga.',
    difficulty: 'hard',
  },
  {
    id: 'e-14',
    tier: 14,
    prize: 500000,
    q: 'Mis oli Eesti krooni ametlik fikseeritud kurss Saksa marga suhtes 1992. aasta rahareformi ajal?',
    choices: ['1 DEM = 4 EEK', '1 DEM = 8 EEK', '1 DEM = 10 EEK', '1 DEM = 15.6466 EEK'],
    correct: 1,
    hostNote: '1 Saksa mark võrdus täpselt 8 Eesti krooniga.',
    difficulty: 'expert',
  },
  {
    id: 'e-15',
    tier: 15,
    prize: 1000000,
    q: 'Kes oli see Liivimaa kroonik, kelle 13. sajandi ladinakeelne kroonika on peamine kirjalik allikas muistse vabadusvõitluse kohta?',
    choices: ['Balthasar Russow', 'Läti Henrik', 'Christian Kelch', 'Thomas Hiärn'],
    correct: 1,
    hostNote: 'Henrici Chronicon Livoniae (Henriku Liivimaa kroonika) kirjutas preester Henrik 1220. aastatel.',
    difficulty: 'expert',
  },
  {
    id: 'e-backup-1',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Mis aastal asutati Tartu Ülikool Rootsi kuninga Gustav II Adolfi poolt?',
    choices: ['1632', '1710', '1802', '1919'],
    correct: 0,
    hostNote: 'Academia Gustaviana asutati 1632. aastal.',
    difficulty: 'medium',
  },
  {
    id: 'e-backup-2',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Mis on Eesti sügavaim järv?',
    choices: ['Rõuge Suurjärv', 'Peipsi järv', 'Võrtsjärv', 'Pühajärv'],
    correct: 0,
    hostNote: 'Rõuge Suurjärve sügavus ulatub 38 meetrini.',
    difficulty: 'hard',
  },
]

export const MILJONAR_PEO_QUESTIONS: MiljonarQuestion[] = [
  {
    id: 'p-1',
    tier: 1,
    prize: 100,
    q: 'Mis värvi on tavaliselt küps banaan?',
    choices: ['Sinine', 'Kollane', 'Lilla', 'Must'],
    correct: 1,
    hostNote: 'Kollane!',
    difficulty: 'easy',
  },
  {
    id: 'p-2',
    tier: 2,
    prize: 200,
    q: 'Milline neist on tuntud lauamäng, kus ostetakse ja ehitatakse kinnisvara?',
    choices: ['Monopoly', 'Scrabble', 'Kabe', 'Twister'],
    correct: 0,
    hostNote: 'Monopoly on maailma kuulsaim kinnisvaramäng.',
    difficulty: 'easy',
  },
  {
    id: 'p-3',
    tier: 3,
    prize: 300,
    q: 'Milline salaagent kannab koodnime 007?',
    choices: ['Jason Bourne', 'Ethan Hunt', 'James Bond', 'Johnny English'],
    correct: 2,
    hostNote: 'James Bond, Tema Majesteedi salateenistuses.',
    difficulty: 'easy',
  },
  {
    id: 'p-4',
    tier: 4,
    prize: 500,
    q: 'Milline bänd laulis kuulsat hitti "Bohemian Rhapsody"?',
    choices: ['The Beatles', 'Queen', 'ABBA', 'Pink Floyd'],
    correct: 1,
    hostNote: 'Queen ja legendaarne Freddie Mercury.',
    difficulty: 'easy',
  },
  {
    id: 'p-5',
    tier: 5,
    prize: 1000,
    q: 'Mitu silma on kokku kahel tavalisel kuuetahulisel mängutäringul?',
    choices: ['21', '36', '42', '48'],
    correct: 2,
    hostNote: 'Ühel täringul on 1+2+3+4+5+6 = 21 silma. Kahel täringul kokku 42 silma!',
    difficulty: 'easy',
  },
  {
    id: 'p-6',
    tier: 6,
    prize: 2000,
    q: 'Millises filmisarjas astuvad üles tegelased Neo, Morpheus ja Trinity?',
    choices: ['Sõrmuste Isand', 'Matrix', 'Tähesõjad', 'Terminaator'],
    correct: 1,
    hostNote: 'Wachowskite lavastatud ikooniline ulmesari Matrix.',
    difficulty: 'medium',
  },
  {
    id: 'p-7',
    tier: 7,
    prize: 4000,
    q: 'Milline kokteil koosneb viinast, ingveriõllest ja laimimahlast vasktopsis?',
    choices: ['Mojito', 'Moscow Mule', 'Margarita', 'Cosmopolitan'],
    correct: 1,
    hostNote: 'Moscow Mule serveeritakse traditsiooniliselt külmas vaskkruusis.',
    difficulty: 'medium',
  },
  {
    id: 'p-8',
    tier: 8,
    prize: 8000,
    q: 'Mis riigist on pärit maailmakuulus pitsa ja pasta kodumaa?',
    choices: ['Kreeka', 'Prantsusmaa', 'Itaalia', 'Hispaania'],
    correct: 2,
    hostNote: 'Itaalia, Napoli on pitsa sünnikodu.',
    difficulty: 'medium',
  },
  {
    id: 'p-9',
    tier: 9,
    prize: 16000,
    q: 'Mis aastal jõudis kinodesse James Cameroni film "Avatar", mis purustas kõik kassarekordid?',
    choices: ['2005', '2009', '2012', '2015'],
    correct: 1,
    hostNote: 'Avatar linastus 2009. aasta detsembris.',
    difficulty: 'medium',
  },
  {
    id: 'p-10',
    tier: 10,
    prize: 32000,
    q: 'Mitu klahvi on standardse täismõõdulise tiibklaveri klaviatuuril?',
    choices: ['76', '84', '88', '92'],
    correct: 2,
    hostNote: 'Standardklaveril on 88 klahvi (52 valget ja 36 musta).',
    difficulty: 'hard',
  },
  {
    id: 'p-11',
    tier: 11,
    prize: 64000,
    q: 'Milline Rootsi popgrupp võitis 1974. aasta Eurovisiooni lauluga "Waterloo"?',
    choices: ['Roxette', 'ABBA', 'Ace of Base', 'Europe'],
    correct: 1,
    hostNote: 'ABBA triumfeeris Brightonis toimunud Eurovisioonil.',
    difficulty: 'hard',
  },
  {
    id: 'p-12',
    tier: 12,
    prize: 125000,
    q: 'Kes lavastas kultusfilmi "Pulp Fiction" (1994)?',
    choices: ['Martin Scorsese', 'Quentin Tarantino', 'Steven Spielberg', 'David Fincher'],
    correct: 1,
    hostNote: 'Quentin Tarantino võitis filmiga Cannes\'i Kuldse Palmioksa.',
    difficulty: 'hard',
  },
  {
    id: 'p-13',
    tier: 13,
    prize: 250000,
    q: 'Milline oli esimene mängukonsool, mida müüdi üle 100 miljoni eksemplari?',
    choices: ['Nintendo Entertainment System', 'PlayStation (PS1)', 'Game Boy', 'Nintendo DS'],
    correct: 1,
    hostNote: 'Originaalne Sony PlayStation (1994) ületas esimesena 100 miljoni piiri (102,4 mln).',
    difficulty: 'hard',
  },
  {
    id: 'p-14',
    tier: 14,
    prize: 500000,
    q: 'Millises riigis asub maailma vanim siiani tegutsev restoran Sobrino de Botín (asutatud 1725)?',
    choices: ['Prantsusmaal (Pariis)', 'Hispaanias (Madrid)', 'Itaalias (Rooma)', 'Suurbritannias (London)'],
    correct: 1,
    hostNote: 'Sobrino de Botín asub Madridi vanalinnas ja Guinessi rekordite raamat peab seda vanimaks pidevalt tegutsenud restoraniks.',
    difficulty: 'expert',
  },
  {
    id: 'p-15',
    tier: 15,
    prize: 1000000,
    q: 'Milline oli maailma esimese avaliku YouTube\'i video ("Me at the zoo") täpne pikkus?',
    choices: ['11 sekundit', '19 sekundit', '32 sekundit', '48 sekundit'],
    correct: 1,
    hostNote: 'Jawed Karimi üles laaditud San Diego loomaaia elevandivideo kestab täpselt 19 sekundit.',
    difficulty: 'expert',
  },
  {
    id: 'p-backup-1',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Milline loom on tegelane Nemo kuulsas Pixari animafilmis?',
    choices: ['Kuldhai', 'Klounkala', 'Meduus', 'Merihobune'],
    correct: 1,
    hostNote: 'Nemo on oranž-valge klounkala.',
    difficulty: 'easy',
  },
  {
    id: 'p-backup-2',
    tier: 0,
    prize: 0,
    backup: true,
    q: 'Milline jook leiutati 1886. aastal dr John Pembertoni poolt Atlantas?',
    choices: ['Coca-Cola', 'Pepsi', 'Dr Pepper', 'Sprite'],
    correct: 0,
    hostNote: 'Farmatseut John Pemberton lõi algselt ravijoogina Coca-Cola siirupi.',
    difficulty: 'medium',
  },
]
